### ISSUE TITLE
problem with left join in file merge_data.R

### ISSUE THREAD

**Issue by ghost** [joachim-gassen/tidy_covid19#1]
# left_join numeric df is good
cases %>%
+ left_join(
+     read_csv("data/gtrends_country_day.csv", col_types = cols()) %>%
+       mutate(date = ymd(date)),
+     by = c("iso3c", "date")
+   ) %>%
+   left_join(
+     read_csv("data/gtrends_country.csv", col_types = cols()) %>%
+       rename(gtrends_country_score = gtrends_score),
+     by = c("iso3c")
+   ) %>%
+   left_join(
+     read_csv("data/wbank.csv", col_types = cols()),
+     by = "iso3c"
+   )  -> raw_sample

left_join with category vars.... it no works

cases %>%
+   left_join(
+     calc_npi_measure("Social distancing", "soc_dist"), 
+     by = c("iso3c", "date")
+   )
Error: cannot join a Date object with an object that is not a Date object
Called from: left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches, environment())
Browse[1]> c

**Comment by joachim-gassen** [comment]
Hi there:

This is hard for me to figure out without additional help. I looks as if something is wrong with your `npi` dataframe leading to `calc_npi_measure()` returning an ill-formatted dataframe.

Can you run the following within your project:

```
library(tidyverse)
library(lubridate)

read_csv("data/acaps_npi.csv", col_types = cols()) %>%
  mutate(npi_date = ymd(date_implemented)) %>%
  rename (npi_type = category) %>%
  select(iso3c, npi_date, npi_type) -> npi

str(npi)
```

and paste the output here?

If this looks something like

```
Classes ‘spec_tbl_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':	2387 obs. of  3 variables:
 $ iso3c   : chr  "AFG" "AFG" "AFG" "AFG" ...
 $ npi_date: Date, format: "2020-02-12" "2020-02-12" "2020-02-12" ...
 $ npi_type: chr  "Public health measures" "Public health measures" "Public health measures" "Social and economic measures" ...
```
your `npi` data frame should be fine.

Then, after parsing the function `calc_npi_measure()`, can you please run

```
library(tidyverse)
library(lubridate)

cases <- read_csv("data/jh_covid19_ctry_level.csv", 
                  col_types = cols()) %>%
  mutate(date = ymd(date))

df <- calc_npi_measure("Social distancing", "soc_dist")

str(df)
```

And again pars its content here?

It should look like

```
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	11658 obs. of  3 variables:
 $ iso3c   : chr  "AFG" "AFG" "AFG" "AFG" ...
 $ date    : Date, format: "2020-01-22" "2020-01-23" "2020-01-24" ...
 $ soc_dist: num  0 0 0 0 0 0 0 0 0 0 ...
```

Thanks!

**Comment by joachim-gassen** [comment]
Closing this due to lack of response...
