### ISSUE TITLE
updated to R 4.0 and package does not work!

### ISSUE THREAD

**Issue by wabee** [joachim-gassen/tidy_covid19#2]

**Comment by joachim-gassen** [comment]
Thank you for your feedback but this is not a package repository but a simple code repo to showcase how to pull and clean Coivd-19 related data. 

Did you mean to open an issue on {tidycovid19} package (https://github.com/joachim-gassen/tidycovid19)? If yes, then do so but please provide some more info (what fails, error messages that you encountered during install or using the package) as this will help me to track down the issue.

Closing this as off-topic for the time being.
